return {
PlaceObj('ModItemCode', {
	'name', "ESS_Init",
	'comment', "ESS_Init",
	'FileName', "Code/ESS_Init.lua",
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 9000,
	challenge_mod = 20,
	comment = "Astrogeologist(Override)",
	display_name = T(879264436898, --[[ModItemCommanderProfilePreset Default astrogeologist display_name]] "Astrogeologist"),
	effect = T(613799555628, --[[ModItemCommanderProfilePreset Default astrogeologist effect]] "- Start with a Rare Metal deposit revealed\n- Extractor production increased by 10%\n- Bonus Tech: <color em>Deep Scanning</color> (allows the scanning of sectors for deep deposits)"),
	group = "Default",
	id = "astrogeologist",
	PlaceObj('Effect_ModifyLabel', {
		Label = "WaterExtractor",
		Percent = 10,
		Prop = "water_production",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "MetalsExtractor",
		Percent = 10,
		Prop = "production_per_day1",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "PreciousMetalsExtractor",
		Percent = 10,
		Prop = "production_per_day1",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "RegolithExtractor",
		Percent = 10,
		Prop = "production_per_day1",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Physics",
		Research = "DeepScanning",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 3000,
	challenge_mod = 20,
	comment = "Hydro Engineer(Override)",
	display_name = T(352207757388, --[[ModItemCommanderProfilePreset Default hydroengineer display_name]] "Hydro Engineer"),
	effect = T(735315286643, --[[ModItemCommanderProfilePreset Default hydroengineer effect]] "- Start with a Water deposit revealed\n- Domes consume 25% less Water\n- Bonus Tech: <color em>Water Reclamation</color> (unlocks a spire which reduces Water consumption)"),
	group = "Default",
	id = "hydroengineer",
	PlaceObj('Effect_ModifyLabel', {
		Label = "Dome",
		Percent = -25,
		Prop = "water_consumption",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Biotech",
		Research = "WaterReclamation",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 4000,
	challenge_mod = 10,
	comment = "Doctor(Override)",
	display_name = T(334778545379, --[[ModItemCommanderProfilePreset Default doctor display_name]] "Doctor"),
	effect = T(773016672904, --[[ModItemCommanderProfilePreset Default doctor effect]] "- Minimum Comfort required for birth lowered by 15\n- Bonus Tech: <color em>Stem Reconstruction</color> (colonist lifespan is increased)"),
	group = "Default",
	id = "doctor",
	PlaceObj('Effect_ModifyLabel', {
		Amount = -15,
		Label = "Consts",
		Prop = "MinComfortBirth",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Biotech",
		Research = "StemReconstruction",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 1000,
	challenge_mod = 10,
	comment = "Inventor(Override)",
	display_name = T(515849436244, --[[ModItemCommanderProfilePreset Default inventor display_name]] "Inventor"),
	effect = T(744710883487, --[[ModItemCommanderProfilePreset Default inventor effect]] "- Drones are gradually optimized to work and construct faster until Sol 100\n- Bonus Tech: <color em>Autonomous Hubs</color> (Drone Hubs no longer require Power or maintenance)"),
	group = "Default",
	id = "inventor",
	PlaceObj('Effect_ModifyLabelOverTime', {
		Label = "Consts",
		Percent = 1,
		Prop = "DroneConstructAmount",
		Repetitions = 50,
		TimeInterval = 2,
		TimeUnits = 720000,
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Breakthroughs",
		Research = "AutonomousHubs",
	}),
	PlaceObj('Effect_ModifyLabelOverTime', {
		Label = "Consts",
		Percent = 1,
		Prop = "DroneBuildingRepairAmount",
		Repetitions = 50,
		TimeInterval = 2,
		TimeUnits = 720000,
	}),
	PlaceObj('Effect_ModifyLabelOverTime', {
		Label = "Consts",
		Percent = -1,
		Prop = "DroneGatherResourceWorkTime",
		Repetitions = 50,
		TimeInterval = 2,
		TimeUnits = 720000,
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 8000,
	challenge_mod = 10,
	comment = "Ecologist(Override)",
	display_name = T(881071428006, --[[ModItemCommanderProfilePreset Default ecologist display_name]] "Ecologist"),
	effect = T(314584298354, --[[ModItemCommanderProfilePreset Default ecologist effect]] "- Service Comfort of decorations increased by 10\n- Bonus Tech: <color em>Hanging Gardens</color> (unlocks a spire which improves residences in the Dome)"),
	group = "Default",
	id = "ecologist",
	PlaceObj('Effect_ModifyLabel', {
		Amount = 10,
		Label = "Decorations",
		Prop = "service_comfort",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Biotech",
		Research = "HangingGardens",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 5000,
	challenge_mod = 10,
	comment = "Psychologist(Override)",
	display_name = T(612037570718, --[[ModItemCommanderProfilePreset Default psychologist display_name]] "Psychologist"),
	effect = T(166483897770, --[[ModItemCommanderProfilePreset Default psychologist effect]] "- Colonists recover 5 additional Sanity while resting in their homes\n- Bonus Tech: <color em>Behavioral Shaping</color> (unlocks a Sanatorium spire which treats colonists' flaws)"),
	group = "Default",
	id = "psychologist",
	param1 = 5,
	PlaceObj('Effect_GrantTech', {
		Field = "Social",
		Research = "BehavioralShaping",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	challenge_mod = 15,
	comment = "Mechanist",
	display_name = T(721704188846, --[[ModItemCommanderProfilePreset Default ESS_Mechanist display_name]] "Mechanist"),
	effect = T(740957652674, --[[ModItemCommanderProfilePreset Default ESS_Mechanist effect]] "- -25% bonus drone building time\n- -25% bonus biorobot building time\n- Bonus Tech: <color em>Drone Printing</color> (You can make drone assembler)"),
	group = "Default",
	id = "ESS_Mechanist",
	tech1 = "DronePrinting",
	PlaceObj('Effect_ModifyLabel', {
		Label = "DroneFactory",
		Percent = -25,
		Prop = "AndroidConstructionTime",
		comment = "Mechanist Drone Construction Time",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "DroneFactory",
		Percent = -25,
		Prop = "AndroidConstructionTime",
		comment = "Mechanist BIorobot Construction Time",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 500,
	challenge_mod = -30,
	comment = "City Mayor(Override)",
	display_name = T(753415763818, --[[ModItemCommanderProfilePreset Default citymayor display_name]] "City Mayor"),
	effect = T(613664886696, --[[ModItemCommanderProfilePreset Default citymayor effect]] "- 2,000 M additional starting funding\n- Buildings require upkeep less often\n- Bonus Tech: <color em>Mars Nouveau</color> (building costs in Metals & Concrete are reduced by 20%)"),
	group = "Default",
	id = "citymayor",
	tech1 = "MarsNoveau",
	PlaceObj('Effect_Funding', {
		Funding = 2000,
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "OutsideBuildings",
		Percent = 20,
		Prop = "maintenance_threshold_base",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "InsideBuildings",
		Percent = 20,
		Prop = "maintenance_threshold_base",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	challenge_mod = 5,
	comment = "Architect",
	display_name = T(757129158586, --[[ModItemCommanderProfilePreset Default ESS_Architect display_name]] "Architect"),
	effect = T(158153484162, --[[ModItemCommanderProfilePreset Default ESS_Architect effect]] "- 15% discount of metal/concrete on construction\n- Bonus Tech: <color em>Smart Home</color> (You can build smart home)"),
	group = "Default",
	id = "ESS_Architect",
	tech1 = "SmartHome",
	PlaceObj('Effect_ModifyLabel', {
		Label = "Building",
		Percent = -20,
		Prop = "construction_cost_Concrete",
		comment = "Architect Construction Cost(Concrete)",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Building",
		Percent = -20,
		Prop = "construction_cost_Metals",
		comment = "Architect Construction Cost(Metals)",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 999999,
	comment = "Random(Override)",
	display_name = T(286720200944, --[[ModItemCommanderProfilePreset Default random display_name]] "Random"),
	group = "Default",
	id = "random",
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 7000,
	challenge_mod = 30,
	comment = "Futurist(Override)",
	display_name = T(679614748394, --[[ModItemCommanderProfilePreset Default author display_name]] "Futurist"),
	effect = T(740054478648, --[[ModItemCommanderProfilePreset Default author effect]] "- Breakthrough techs are researched 30% faster\n- Bonus Tech: <color em>Autonomous Sensors</color> (Sensor Towers no longer require Power or maintenance)"),
	group = "Default",
	id = "author",
	PlaceObj('Effect_ModifyLabel', {
		Amount = -30,
		Label = "Consts",
		Prop = "BreakThroughTechCostMod",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Physics",
		Research = "AutonomousSensors",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 2000,
	challenge_mod = 10,
	comment = "Oligarch(Override)",
	display_name = T(845006760124, --[[ModItemCommanderProfilePreset Default oligarch display_name]] "Oligarch"),
	effect = T(543124075903, --[[ModItemCommanderProfilePreset Default oligarch effect]] "- Fuel production increased by 25%\n- Bonus Tech: <color em>Arcology</color> (unlocks a residential spire)"),
	group = "Default",
	id = "oligarch",
	PlaceObj('Effect_ModifyLabel', {
		Label = "FuelFactory",
		Percent = 25,
		Prop = "production_per_day1",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "Arcology",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 6000,
	comment = "Politician(Override)",
	display_name = T(279436762489, --[[ModItemCommanderProfilePreset Default politician display_name]] "Politician"),
	effect = T(153459232872, --[[ModItemCommanderProfilePreset Default politician effect]] "- All Funding gains are increased by 20%\n- Bonus Tech: <color em>Martian Patents</color> (repeatable tech that grants Funding)"),
	group = "Default",
	id = "politician",
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = 20,
		Prop = "FundingGainsModifier",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Social",
		Research = "MartianPatents",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	challenge_mod = 35,
	comment = "Nuclear Physicist",
	display_name = T(562030489366, --[[ModItemCommanderProfilePreset Default ESS_Nuclear_Physicist display_name]] "Nuclear Physicist"),
	effect = T(256705322461, --[[ModItemCommanderProfilePreset Default ESS_Nuclear_Physicist effect]] "- Every 5 sols, your fusion reactor and artificial sun will be optimized(Total 20 times)\n- Bonus Tech: <color em>Nuclear Fusion</color> (You can build fusion reactor)"),
	group = "Default",
	id = "ESS_Nuclear_Physicist",
	tech1 = "NuclearFusion",
	PlaceObj('Effect_ModifyLabelOverTime', {
		Label = "FusionReactor",
		Percent = 5,
		Prop = "electricity_production",
		Repetitions = 20,
		TimeInterval = 5,
		TimeUnits = 720000,
		comment = "Nuclear Physicist Reactor Optimization(Normal)",
	}),
	PlaceObj('Effect_ModifyLabelOverTime', {
		Label = "ArtificialSun",
		Percent = 5,
		Prop = "electricity_production",
		Repetitions = 20,
		TimeInterval = 5,
		TimeUnits = 720000,
		comment = "Nuclear Physicist Reactor Optimization(Wonder)",
	}),
}),
PlaceObj('ModItemCommanderProfilePreset', {
	SortKey = 10000,
	bonus_rockets = 1,
	challenge_mod = 20,
	comment = "Rocket Scientist(Override)",
	display_name = T(637321121505, --[[ModItemCommanderProfilePreset Default rocketscientist display_name]] "Rocket Scientist"),
	effect = T(692801289483, --[[ModItemCommanderProfilePreset Default rocketscientist effect]] "- Start with an extra Rocket\n- Bonus Tech: <color em>CO2 Jet Propulsion</color> (unlocks Shuttle Hub and long-range transportation)"),
	group = "Default",
	id = "rocketscientist",
	name = "rocketscientist",
	PlaceObj('Effect_GrantTech', {
		Field = "Robotics",
		Research = "CO2JetPropulsion",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = 25,
	comment = "Outsource Banned",
	description = T(749993091016, --[[ModItemGameRules ESS_Outsource_Banned description]] "Name says all, you can not outsource research."),
	display_name = T(693093420949, --[[ModItemGameRules ESS_Outsource_Banned display_name]] "Outsource Banned"),
	group = "Default",
	id = "ESS_Outsource_Banned",
	PlaceObj('Effect_ModifyLabel', {
		Amount = 2,
		Label = "Consts",
		Prop = "OutsourceDisabled",
		comment = "Outsource Banned Disable",
	}),
}),
PlaceObj('ModItemGameRules', {
	comment = "Easy Research EX",
	description = T(237587372454, --[[ModItemGameRules ESS_Easy_Research_EX description]] "90% Tech Cost Discount, also increase research amount a lot."),
	display_name = T(456787358198, --[[ModItemGameRules ESS_Easy_Research_EX display_name]] "Easy Research EX"),
	group = "Default",
	id = "ESS_Easy_Research_EX",
	PlaceObj('Effect_TechBoost', {
		Field = "Biotech",
		Percent = 90,
		comment = "Tech Cost Discount EX Biotech",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Breakthroughs",
		Percent = 90,
		comment = "Tech Cost Discount EX Breakthrough",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Engineering",
		Percent = 90,
		comment = "Tech Cost Discount EX Engineering",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Mysteries",
		Percent = 90,
		comment = "Tech Cost Discount EX Mysteries",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Physics",
		Percent = 90,
		comment = "Tech Cost Discount EX Physics",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Robotics",
		Percent = 90,
		comment = "Tech Cost Discount EX Robotics",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Social",
		Percent = 90,
		comment = "Tech Cost Discount EX Social",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Storybits",
		Percent = 90,
		comment = "Tech Cost Discount EX Storybits",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Amount = 60000,
		Label = "Consts",
		Prop = "SponsorResearch",
		comment = "Tech Cost Discount EX Research Per Day",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = 125,
	comment = "Resource Depletion",
	description = T(434650702747, --[[ModItemGameRules ESS_Resource_Depletion description]] "Cannot import anything"),
	display_name = T(522595423781, --[[ModItemGameRules ESS_Resource_Depletion display_name]] "Resource Depletion"),
	group = "Default",
	id = "ESS_Resource_Depletion",
	PlaceObj('Effect_Code', {
		OnInitEffect = function ()  end,
		comment = "Resource Depletion Lock Import",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = 35,
	comment = "Melancholic World",
	description = T(268622463772, --[[ModItemGameRules ESS_Melancholic_World description]] "Daily Sanity Recover -10"),
	display_name = T(759853071207, --[[ModItemGameRules ESS_Melancholic_World display_name]] "Melancholic World"),
	group = "Default",
	id = "ESS_Melancholic_World",
	PlaceObj('Effect_ModifyLabel', {
		Amount = -10,
		Label = "Colonist",
		Prop = "DailySanityRecover",
		comment = "Melancholic World Sanity Recover",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = 45,
	comment = "Techphobia",
	description = T(107398402046, --[[ModItemGameRules ESS_Techphobia description]] "35% Tech Cost Increase"),
	display_name = T(902274752227, --[[ModItemGameRules ESS_Techphobia display_name]] "Techphobia"),
	group = "Default",
	id = "ESS_Techphobia",
	PlaceObj('Effect_TechBoost', {
		Field = "Biotech",
		Percent = -35,
		comment = "Techphobia Biotech",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Breakthroughs",
		Percent = -35,
		comment = "Techphobia Breakthrough",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Engineering",
		Percent = -35,
		comment = "Techphobia Engineering",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Mysteries",
		Percent = -35,
		comment = "Techphobia Mysteries",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Physics",
		Percent = -35,
		comment = "Techphobia Physics",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Robotics",
		Percent = -35,
		comment = "Techphobia Robotics",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Social",
		Percent = -35,
		comment = "Techphobia Social",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Storybits",
		Percent = -35,
		comment = "Techphobia Storybits",
	}),
}),
PlaceObj('ModItemGameRules', {
	comment = "Free Outsource",
	description = T(158136817592, --[[ModItemGameRules ESS_Free_Outsource description]] "Name says all, free outsource."),
	display_name = T(716790354529, --[[ModItemGameRules ESS_Free_Outsource display_name]] "Free Outsource"),
	group = "Default",
	id = "ESS_Free_Outsource",
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -100,
		Prop = "OutsourceResearchCost",
		comment = "Free Outsource Cost",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = 15,
	comment = "Religion Is Dead",
	description = T(759432455339, --[[ModItemGameRules ESS_Religion_Is_Dead description]] "No religious people can be appeared since religion is dead. (This doesn't applies for Church of the New Ark and Cult of Darkness (WIP) )\nOf course no saint. (This applies for all sponsors)"),
	display_name = T(741343529741, --[[ModItemGameRules ESS_Religion_Is_Dead display_name]] "Religion Is Dead"),
	group = "Default",
	id = "ESS_Religion_Is_Dead",
	PlaceObj('Effect_Code', {
		OnInitEffect = function ()  end,
		comment = "Religion Is Dead No Relgious",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	MachineParts = 15,
	OrbitalProbe = 3,
	Polymers = 10,
	RCSolar = 1,
	RCTransport = 1,
	SortKey = 4001,
	StirlingGenerator = 1,
	banners_name = "China",
	cargo = 50000,
	challenge_mod = 60,
	colony_color_scheme = "red_steel",
	comment = "China(Override)",
	default_logo = "China",
	default_skin = "Star",
	difficulty = T(884501536999, --[[ModItemMissionSponsorPreset Default CNSA difficulty]] "II"),
	display_name = T(372503617594, --[[ModItemMissionSponsorPreset Default CNSA display_name]] "China"),
	effect = T(523400672720, --[[ModItemMissionSponsorPreset Default CNSA effect]] "Research per Sol: 200\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>RC Generator</color> - RC Commander that can generate power as a solar panel\n- <color em>Tai-chi Garden</color> - small exercising garden, visitors recover small amounts of Health and may become Fit\n- Passenger Rockets carry 10 additional Colonists\n- Applicants are generated twice as fast"),
	funding = 8000,
	goal_1_param_1 = "100",
	goal_1_param_2 = "Food",
	goal_2_param_1 = "50",
	goal_3_param_1 = "300",
	goal_4_param_1 = "40",
	goal_4_param_2 = "70",
	goal_5_param_1 = "8",
	goal_image_1 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_pin_image_1 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/drone.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/oval_dome.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/research.tga",
	group = "Default",
	id = "CNSA",
	initial_applicants = 200,
	initial_rockets = 3,
	initial_techs_unlocked = 1,
	lock_name1 = "RCSolar",
	lock_value1 = "unlocked",
	pod_class = "SupplyPod",
	research_points = 200,
	reward_effect_1 = PlaceObj('RewardApplicants', {
		'Amount', 100,
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 30,
		'Prefab', "DronePrefab",
	}),
	reward_effect_3 = PlaceObj('RewardFunding', {
		'Amount', 2000000000,
	}),
	reward_effect_4 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeMedium",
	}),
	reward_effect_5 = PlaceObj('RewardResearchPoints', {
		'Amount', 10000,
	}),
	sponsor_goal_1 = "ProduceResource",
	sponsor_goal_2 = "ColonistsEducate",
	sponsor_goal_3 = "Colonists",
	sponsor_goal_4 = "ColonistsNeeds",
	sponsor_goal_5 = "WorkingDomes",
	sponsor_nation_name1 = "Chinese",
	sponsor_nation_percent1 = 100,
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -50,
		Prop = "ApplicantGenerationInterval",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Amount = 10,
		Label = "Consts",
		Prop = "MaxColonistsPerRocket",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	ExplorerRover = 1,
	FuelFactory = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 3,
	Polymers = 10,
	SortKey = 10001,
	StirlingGenerator = 1,
	anomaly_bonus_breakthrough = range(2, 4),
	applicants_per_breakthrough = 30,
	banners_name = "paradox",
	cargo = 50000,
	challenge_mod = 200,
	colony_color_scheme = "blue_sky",
	comment = "Paradox Interactive(Override)",
	default_logo = "Paradox",
	default_skin = "Star",
	difficulty = T(726598504980, --[[ModItemMissionSponsorPreset Default paradox difficulty]] "IV"),
	display_name = T(916055014101, --[[ModItemMissionSponsorPreset Default paradox display_name]] "Paradox Interactive"),
	effect = T(516468140052, --[[ModItemMissionSponsorPreset Default paradox effect]] "Research per Sol: 100\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Jumper Shuttle</color> - faster shuttles that use parabolic trajectories\n- <color em>Game Developer</color> - produces games which grant funding depending on their success\n- Discover more Breakthrough Anomalies\n- Researching a Breakthrough Tech grants Applicants\n- Rockets require more fuel to launch <color em>(drawback)</color>"),
	filter = function ()  end,
	goal_1_param_1 = "2",
	goal_2_param_1 = "15",
	goal_3_param_1 = "30",
	goal_4_param_1 = "DomeMega",
	goal_5_param_1 = "9",
	goal_image_1 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_01.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/supply_pod.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/jumper_shuttle_hub.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/rocket.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/research.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/funding.tga",
	group = "Default",
	id = "paradox",
	initial_applicants = 75,
	initial_rockets = 1,
	initial_techs_unlocked = 1,
	pod_class = "SupplyPod",
	precious_metals_export_price = 24,
	reward_effect_1 = PlaceObj('RewardSupplyPods', {
		'Amount', 5,
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "JumperShuttleHub",
	}),
	reward_effect_3 = PlaceObj('RewardNewRocket', nil),
	reward_effect_4 = PlaceObj('RewardResearchPoints', {
		'Amount', 10000,
	}),
	reward_effect_5 = PlaceObj('RewardFunding', {
		'Amount', 3000000000,
	}),
	sponsor_goal_1 = "CompleteBreakthroughs",
	sponsor_goal_2 = "LandColonistsBySol",
	sponsor_goal_3 = "AnalyzeAnomalies",
	sponsor_goal_4 = "SingleBuilding",
	sponsor_goal_5 = "CompleteBreakthroughs",
	sponsor_nation_name1 = "Swedish",
	sponsor_nation_name2 = "German",
	sponsor_nation_name3 = "English",
	sponsor_nation_name4 = "French",
	sponsor_nation_percent1 = 60,
	sponsor_nation_percent2 = 10,
	sponsor_nation_percent3 = 20,
	sponsor_nation_percent4 = 10,
	PlaceObj('Effect_ModifyLabel', {
		Amount = 30,
		Label = "AllRockets",
		Prop = "launch_fuel",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	comment = "TestRival",
	default_logo = "SurvivingMars",
	display_name = T(197971843740, --[[ModItemMissionSponsorPreset Default TestRival display_name]] "Test Rival"),
	group = "Default",
	id = "TestRival",
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 2,
	Electronics = 10,
	ExplorerRover = 1,
	FuelFactory = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 2,
	Polymers = 10,
	RCSensor = 1,
	SortKey = 6001,
	StirlingGenerator = 1,
	banners_name = "Europe",
	cargo = 50000,
	challenge_mod = 110,
	comment = "Europe(Override)",
	default_logo = "Europe",
	display_name = T(478135254926, --[[ModItemMissionSponsorPreset Default ESA display_name]] "Europe"),
	effect = T(545764029023, --[[ModItemMissionSponsorPreset Default ESA effect]] "Research per Sol: 400\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>RC Seeker</color> - RC Commander that works as a sensor tower when stationary\n- <color em>Low-G Lab</color> - a research building that is built outside domes and reduces the cost of Biotech and Physics techs\n- 5 extra starting technologies\n- Gain Funding every time a tech is researched. Gain double if it's a Breakthrough tech"),
	funding = 6000,
	funding_per_breakthrough = 300,
	funding_per_tech = 150,
	goal_1_param_1 = "5",
	goal_1_param_2 = "Physics",
	goal_2_param_1 = "20",
	goal_2_param_2 = "scientist",
	goal_3_param_1 = "2",
	goal_3_param_2 = "ScienceInstitute",
	goal_3_param_3 = "",
	goal_4_param_1 = "50",
	goal_4_param_2 = "scientist",
	goal_5_param_1 = "10000",
	goal_image_1 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/triboelectric_schrubbe.tga",
	goal_pin_image_2 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/network_node.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/rocket.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/funding.tga",
	group = "Default",
	id = "ESA",
	initial_techs_unlocked = 2,
	lock_name1 = "RCSensor",
	lock_value1 = "unlocked",
	pod_class = "SupplyPod",
	precious_metals_export_price = 22,
	research_points = 400,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "TriboelectricScrubber",
	}),
	reward_effect_2 = PlaceObj('RewardApplicants', {
		'Amount', 3,
		'Trait', "Genius",
	}),
	reward_effect_3 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "NetworkNode",
	}),
	reward_effect_4 = PlaceObj('RewardNewRocket', nil),
	reward_effect_5 = PlaceObj('RewardFunding', {
		'Amount', 3000000000,
	}),
	sponsor_goal_1 = "CompleteFieldTechs",
	sponsor_goal_2 = "ColonistsSpecialists",
	sponsor_goal_3 = "MultipleBuildings",
	sponsor_goal_4 = "MartianbornSpecialists",
	sponsor_goal_5 = "GenerateDailyRP",
	sponsor_nation_name1 = "German",
	sponsor_nation_name2 = "French",
	sponsor_nation_name3 = "Swedish",
	sponsor_nation_name4 = "Bulgarian",
	sponsor_nation_percent1 = 40,
	sponsor_nation_percent2 = 30,
	sponsor_nation_percent3 = 20,
	sponsor_nation_percent4 = 10,
}),
PlaceObj('ModItemMissionSponsorPreset', {
	AdvancedOrbitalProbe = 2,
	Drone = 4,
	DroneHub = 1,
	Electronics = 15,
	ExplorerRover = 1,
	FuelFactory = 1,
	MachineParts = 20,
	Polymers = 15,
	RCRover = 1,
	RCTransport = 1,
	SortKey = 2001,
	StirlingGenerator = 2,
	banners_name = "USA",
	cargo = 70000,
	challenge_mod = 40,
	comment = "USA(Override)",
	default_logo = "USA",
	difficulty = T(212076190679, --[[ModItemMissionSponsorPreset Default NASA difficulty]] "II"),
	display_name = T(879006310569, --[[ModItemMissionSponsorPreset Default NASA display_name]] "USA"),
	effect = T(482237458417, --[[ModItemMissionSponsorPreset Default NASA effect]] "Research per Sol: 300\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Zeus Rocket</color> - increased rocket payload (<cargo> kg)\n- <color em>Advanced Orbital Probe</color> - scans five sectors\n- <color em>Megamall</color> - service building that satisfies most interests\n- Periodic additional funding"),
	funding = 8000,
	goal_1_param_1 = "5",
	goal_2_param_1 = "10",
	goal_3_param_1 = "2000",
	goal_4_param_1 = "5",
	goal_5_param_1 = "30",
	goal_image_1 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_07.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/research.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/supply_pod.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/mega_trigon_dome.tga",
	goal_pin_image_4 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/research_lab.tga",
	group = "Default",
	id = "NASA",
	initial_rockets = 3,
	initial_techs_unlocked = 1,
	pod_class = "SupplyPod",
	research_points = 300,
	reward_effect_1 = PlaceObj('RewardSponsorResearch', {
		'Amount', 100,
		'ModifyId', "SponsorGoals",
	}),
	reward_effect_2 = PlaceObj('RewardSupplyPods', {
		'Amount', 5,
	}),
	reward_effect_3 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeMegaTrigon",
	}),
	reward_effect_4 = PlaceObj('RewardApplicants', {
		'Amount', 3,
		'Trait', "Genius",
	}),
	reward_effect_5 = PlaceObj('RewardPrefab', {
		'Amount', 2,
		'Prefab', "ScienceInstitute",
	}),
	rocket_class = "ZeusRocket",
	sponsor_goal_1 = "AnalyzeAnomalies",
	sponsor_goal_2 = "CompleteTechs",
	sponsor_goal_3 = "GenerateDailyRP",
	sponsor_goal_4 = "CompleteBreakthroughs",
	sponsor_goal_5 = "DeepScanSectors",
	sponsor_nation_name1 = "American",
	sponsor_nation_name2 = "German",
	sponsor_nation_name3 = "English",
	sponsor_nation_percent1 = 90,
	sponsor_nation_percent2 = 5,
	sponsor_nation_percent3 = 5,
	PlaceObj('Effect_ModifyLabel', {
		Amount = 500,
		Label = "Consts",
		Prop = "SponsorFundingPerInterval",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 8,
	DroneHub = 1,
	Electronics = 10,
	FuelFactory = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 1,
	Polymers = 10,
	RCTransport = 1,
	SortKey = 8001,
	StirlingGenerator = 1,
	banners_name = "NewArk",
	cargo = 50000,
	challenge_mod = 250,
	comment = "Churnch of the New Ark(Override)",
	default_logo = "NewArk",
	difficulty = T(186273629348, --[[ModItemMissionSponsorPreset Default NewArk difficulty]] "IV"),
	display_name = T(767708540017, --[[ModItemMissionSponsorPreset Default NewArk display_name]] "Church of the New Ark"),
	effect = T(240671815278, --[[ModItemMissionSponsorPreset Default NewArk effect]] "Research per Sol: 35\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Ark Pod</color> - a supply pod that can carry passengers\n- <color em>Temple Spire</color> - a service spire that satisfies Social interests and restores Sanity to visitors\n- All Colonists have the Religious trait\n- Birthrate is doubled\n- Hydroponic Farms performance reduced by 25 <color em>(drawback)</color>"),
	goal_1_param_1 = "50",
	goal_1_param_2 = "Food",
	goal_2_param_1 = "10",
	goal_2_param_2 = "90",
	goal_3_param_1 = "20",
	goal_3_param_2 = "50",
	goal_4_param_1 = "40",
	goal_4_param_2 = "Electronics",
	goal_5_param_1 = "120",
	goal_5_param_2 = "80",
	goal_image_1 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/research.tga",
	goal_pin_image_3 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/rocket.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/funding.tga",
	group = "Default",
	id = "NewArk",
	initial_applicants = 120,
	initial_rockets = 1,
	initial_techs_unlocked = 1,
	passenger_pod_class = "ArkPod",
	pod_class = "SupplyPod",
	precious_metals_export_price = 20,
	research_points = 35,
	reward_effect_1 = PlaceObj('RewardFunding', nil),
	reward_effect_2 = PlaceObj('RewardSponsorResearch', {
		'Amount', 100,
	}),
	reward_effect_3 = PlaceObj('RewardApplicants', {
		'Amount', 3,
		'Trait', "Saint",
	}),
	reward_effect_4 = PlaceObj('RewardNewRocket', nil),
	reward_effect_5 = PlaceObj('RewardFunding', {
		'Amount', 3000000000,
	}),
	sponsor_goal_1 = "ProduceResource",
	sponsor_goal_2 = "FoundersComfort",
	sponsor_goal_3 = "MartianbornTimed",
	sponsor_goal_4 = "ProduceResource",
	sponsor_goal_5 = "ColonistsNeeds",
	sponsor_nation_name1 = "American",
	sponsor_nation_name2 = "English",
	sponsor_nation_percent1 = 95,
	sponsor_nation_percent2 = 5,
	trait = "Religious",
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -50,
		Prop = "BirthThreshold",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "HydroponicFarm",
		Percent = -25,
		Prop = "performance",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	FuelFactory = 1,
	MachineParts = 20,
	MoistureVaporator = 1,
	OrbitalProbe = 1,
	Polymers = 10,
	RCDriller = 1,
	SortKey = 9001,
	StirlingGenerator = 1,
	banners_name = "Russia",
	cargo = 50000,
	challenge_mod = 200,
	colony_color_scheme = "red_steel",
	comment = "Russia(Override)",
	default_logo = "Russia",
	default_skin = "Facet",
	difficulty = T(357650254565, --[[ModItemMissionSponsorPreset Default Roscosmos difficulty]] "IV"),
	display_name = T(196480541520, --[[ModItemMissionSponsorPreset Default Roscosmos display_name]] "Russia"),
	effect = T(855578901548, --[[ModItemMissionSponsorPreset Default Roscosmos effect]] "Research per Sol: 200\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>RC Driller</color> - a special rover that can extract resources from underground deposits but wastes some of the deposit\n- <color em>Concrete Plant</color> - an automated extractor that produces concrete without the need of a deposit but consumes fuel\n- Bonus Tech: <color em>Fueled Extractors</color> (extractor upgrade that boosts production but consumes Fuel)\n- Fueled Extractors upgrade is free\n- Fuel Refinery prefab costs 50% less\n- Rockets have extended travel time <color em>(drawback)</color>"),
	funding = 5000,
	goal_1_param_1 = "8",
	goal_2_param_1 = "50",
	goal_2_param_2 = "Concrete",
	goal_3_param_1 = "200",
	goal_3_param_2 = "Metals",
	goal_4_param_1 = "3",
	goal_4_param_2 = "160",
	goal_5_param_1 = "50",
	goal_image_1 = "UI/Messages/Goals/mission_goal_07.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_04.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/supply_pod.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/apartments.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/res_all.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/research.tga",
	group = "Default",
	id = "Roscosmos",
	initial_techs_unlocked = 1,
	lock_name1 = "RCDriller",
	lock_value1 = "unlocked",
	modifier_name1 = "FuelFactory",
	modifier_value1 = -50,
	pod_class = "SupplyPod",
	precious_metals_export_price = 22,
	research_points = 200,
	reward_effect_1 = PlaceObj('RewardSupplyPods', {
		'Amount', 8,
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 4,
		'Prefab', "Apartments",
	}),
	reward_effect_3 = PlaceObj('RewardFunding', {
		'Amount', 2000000000,
	}),
	reward_effect_4 = PlaceObj('RewardExportPrice', {
		'Percent', 40,
		'ModifyId', "SponsorGoals",
	}),
	reward_effect_5 = PlaceObj('RewardResearchPoints', {
		'Amount', 10000,
	}),
	sponsor_goal_1 = "Deposits",
	sponsor_goal_2 = "ProduceResourceInASol",
	sponsor_goal_3 = "ProduceUndergroundResource",
	sponsor_goal_4 = "ExtractorPerformance",
	sponsor_goal_5 = "DeepScanSectors",
	sponsor_nation_name1 = "Russian",
	sponsor_nation_name2 = "Bulgarian",
	sponsor_nation_percent1 = 95,
	sponsor_nation_percent2 = 5,
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = 100,
		Prop = "TravelTimeEarthMars",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Robotics",
		Research = "FueledExtractors",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = 100,
		Prop = "TravelTimeMarsEarth",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 4,
	DroneHub = 2,
	Electronics = 10,
	MachineParts = 10,
	OrbitalProbe = 2,
	Polymers = 10,
	RCTransport = 1,
	SortKey = 7001,
	StirlingGenerator = 1,
	banners_name = "SpaceY",
	cargo = 40000,
	challenge_mod = 130,
	colony_color_scheme = "blue_sky",
	comment = "SpaceY(Override)",
	default_logo = "SpaceY",
	default_skin = "Facet",
	difficulty = T(911724823505, --[[ModItemMissionSponsorPreset Default SpaceY difficulty]] "III"),
	display_name = T(614339385419, --[[ModItemMissionSponsorPreset Default SpaceY display_name]] "SpaceY"),
	effect = T(667340967226, --[[ModItemMissionSponsorPreset Default SpaceY effect]] "Research per Sol: 200\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Dragon Rocket</color> - has smaller cargo capacity (<cargo>) but is faster and requires less fuel\n- <color em>Solar Array</color> - a large cluster of solar panels that have lower maintenance cost but are vulnerable to dust storms\n- Drone Hubs start with additional Drones\n- 50% cheaper advanced resources"),
	funding = 6000,
	goal_1_param_1 = "100000",
	goal_3_param_1 = "8",
	goal_3_param_2 = "Engineering",
	goal_4_param_1 = "7",
	goal_5_param_1 = "3",
	goal_5_param_2 = "BioroboticsWorkshop",
	goal_image_1 = "UI/Messages/Goals/mission_goal_01.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/atomic_batteries.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/drone.tga",
	goal_pin_image_3 = "UI/Icons/Colonists/Femaleengineer.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/research.tga",
	group = "Default",
	id = "SpaceY",
	initial_applicants = 75,
	initial_rockets = 5,
	initial_techs_unlocked = 1,
	modifier_name1 = "Polymers",
	modifier_name2 = "Electronics",
	modifier_name3 = "MachineParts",
	modifier_value1 = -50,
	modifier_value2 = -50,
	modifier_value3 = -50,
	pod_class = "SupplyPod",
	precious_metals_export_price = 20,
	research_points = 200,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "AtomicBattery",
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 15,
		'Prefab', "DronePrefab",
	}),
	reward_effect_3 = PlaceObj('RewardApplicants', {
		'Amount', 20,
		'Trait', "Workaholic",
		'Specialization', "engineer",
	}),
	reward_effect_4 = PlaceObj('RewardFunding', {
		'Amount', 2000000000,
	}),
	reward_effect_5 = PlaceObj('RewardResearchPoints', {
		'Amount', 10000,
	}),
	rocket_class = "DragonRocket",
	sponsor_goal_1 = "GeneratePower",
	sponsor_goal_2 = "RefuelRocketInASol",
	sponsor_goal_3 = "CompleteFieldTechs",
	sponsor_goal_4 = "AnalyzePlanetaryAnomalies",
	sponsor_goal_5 = "MultipleBuildings",
	sponsor_nation_name1 = "American",
	sponsor_nation_name2 = "Chinese",
	sponsor_nation_name3 = "Russian",
	sponsor_nation_name4 = "French",
	sponsor_nation_percent1 = 80,
	sponsor_nation_percent2 = 10,
	sponsor_nation_percent3 = 5,
	sponsor_nation_percent4 = 5,
	PlaceObj('Effect_ModifyLabel', {
		Amount = 20,
		Label = "Consts",
		Prop = "CommandCenterMaxDrones",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Amount = 4,
		Label = "DroneHub",
		Prop = "starting_drones",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	FuelFactory = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 3,
	Polymers = 10,
	RCTransport = 1,
	SortKey = 7500,
	StirlingGenerator = 1,
	banners_name = "Brazil",
	cargo = 50000,
	challenge_mod = 100,
	colonist_funding_on_arrival = 10000000,
	colony_color_scheme = "rainforest",
	comment = "Brazil(Override)",
	default_logo = "Brazil",
	default_skin = "Star",
	difficulty = T(540874212694, --[[ModItemMissionSponsorPreset Default Brazil difficulty]] "III"),
	display_name = T(168832028179, --[[ModItemMissionSponsorPreset Default Brazil display_name]] "Brazil"),
	effect = T(312947167422, --[[ModItemMissionSponsorPreset Default Brazil effect]] "Research per Sol: 100\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Large Supply Pod</color> - special supply pod that can carry more cargo\n- <color em>Rare Metals Refinery</color> - turns waste rock into rare metals\n- Colonists grant funding when they arrive on Mars\n- Passages cost no resources and are constructed instantly\n- Colonists suffer no penalties when using passages to work or visit connected domes\n- 5 free Large Supply Pods"),
	funding = 9000,
	game_apply = function ()  end,
	goal_1_param_1 = "15",
	goal_2_param_1 = "60",
	goal_2_param_2 = "30",
	goal_3_param_1 = "4",
	goal_4_param_1 = "3",
	goal_5_param_1 = "200",
	goal_image_1 = "UI/Messages/Goals/mission_goal_01.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/research.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/drop_pod.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/fusion_reactor.tga",
	goal_pin_image_4 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/funding.tga",
	group = "Default",
	id = "Brazil",
	initial_rockets = 1,
	initial_techs_unlocked = 1,
	new_in = "gagarin",
	pod_class = "DropPod",
	precious_metals_export_price = 35,
	reward_effect_1 = PlaceObj('RewardResearchPoints', {
		'Amount', 4000,
	}),
	reward_effect_2 = PlaceObj('RewardSupplyPods', {
		'Amount', 10,
	}),
	reward_effect_3 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "FusionReactor",
	}),
	reward_effect_4 = PlaceObj('RewardApplicants', {
		'Amount', 3,
		'Trait', "Celebrity",
	}),
	reward_effect_5 = PlaceObj('RewardFunding', {
		'Amount', 3000000000,
	}),
	sponsor_goal_1 = "LandColonistsBySol",
	sponsor_goal_2 = "ExportRareMetalsTimed",
	sponsor_goal_3 = "DomeSpires",
	sponsor_goal_4 = "HaveConnectedDomes",
	sponsor_goal_5 = "DomeResidents",
	sponsor_nation_name1 = "Brazilian",
	sponsor_nation_percent1 = 100,
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -100,
		Prop = "NonHomeDomeServiceThresholdDecrement",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -100,
		Prop = "NonHomeDomePerformancePenalty",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	FuelFactory = 1,
	MachineParts = 15,
	OrbitalProbe = 8,
	Polymers = 10,
	RCHarvester = 1,
	SortKey = 3001,
	StirlingGenerator = 1,
	applicants_price = 500000000,
	banners_name = "BlueSun",
	cargo = 50000,
	challenge_mod = 50,
	colony_color_scheme = "blue_sky",
	comment = "Blue Sun Corporation(Override)",
	default_logo = "BlueSun",
	default_skin = "Facet",
	difficulty = T(571485817354, --[[ModItemMissionSponsorPreset Default BlueSun difficulty]] "II"),
	display_name = T(323872034445, --[[ModItemMissionSponsorPreset Default BlueSun display_name]] "Blue Sun Corporation"),
	effect = T(716144341216, --[[ModItemMissionSponsorPreset Default BlueSun effect]] "Research per Sol: 100\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>RC Harvester</color> - transporter rover that can harvest concrete from regolith deposits\n- <color em>Corporate Office</color> - employs workers and generates funding\n- Can buy Applicants with funding\n- Additional Rockets are significantly cheaper\n- Probes can discover deep Rare Metal deposits\n- Bonus Tech: <color em>Deep Metal Extraction</color> (can extract deep metals and deep rare metals deposits)"),
	funding = 10000,
	goal_1_param_1 = "5000000000",
	goal_2_param_1 = "2000000000",
	goal_3_param_1 = "5",
	goal_3_param_2 = "SmartHome",
	goal_4_param_1 = "20",
	goal_4_param_2 = "Tourist",
	goal_5_param_1 = "10000000000",
	goal_5_param_2 = "5",
	goal_image_1 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/stirling_generator.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_3 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_4 = "UI/Icons/Colonists/Malenone.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/research.tga",
	group = "Default",
	id = "BlueSun",
	initial_techs_unlocked = 1,
	lock_name1 = "RCHarvester",
	lock_value1 = "unlocked",
	pod_class = "SupplyPod",
	precious_metals_export_price = 30,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 2,
		'Prefab', "StirlingGenerator",
	}),
	reward_effect_2 = PlaceObj('RewardFunding', nil),
	reward_effect_3 = PlaceObj('RewardApplicants', {
		'Amount', 5,
		'Trait', "Celebrity",
	}),
	reward_effect_4 = PlaceObj('RewardApplicants', {
		'Amount', 60,
		'Trait', "Tourist",
	}),
	reward_effect_5 = PlaceObj('RewardResearchPoints', {
		'Amount', 10000,
	}),
	rocket_price = 500000000,
	sponsor_goal_1 = "SpendFunding",
	sponsor_goal_2 = "ExportProfit",
	sponsor_goal_3 = "MultipleBuildings",
	sponsor_goal_4 = "ColonistsWithTrait",
	sponsor_goal_5 = "GenerateFundingTimed",
	sponsor_nation_name1 = "American",
	sponsor_nation_name2 = "German",
	sponsor_nation_name3 = "Chinese",
	sponsor_nation_name4 = "French",
	sponsor_nation_percent1 = 40,
	sponsor_nation_percent2 = 20,
	sponsor_nation_percent3 = 20,
	sponsor_nation_percent4 = 20,
	PlaceObj('Effect_GrantTech', {
		Field = "Physics",
		Research = "DeepMetalExtraction",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	MachineParts = 15,
	MoistureVaporator = 2,
	OrbitalProbe = 1,
	Polymers = 15,
	RCConstructor = 1,
	SortKey = 5001,
	StirlingGenerator = 1,
	banners_name = "India",
	cargo = 50000,
	challenge_mod = 90,
	comment = "India(Override)",
	default_logo = "India",
	default_skin = "Star",
	difficulty = T(268990754085, --[[ModItemMissionSponsorPreset Default ISRO difficulty]] "III"),
	display_name = T(764101239206, --[[ModItemMissionSponsorPreset Default ISRO display_name]] "India"),
	effect = T(203829566414, --[[ModItemMissionSponsorPreset Default ISRO effect]] "Research per Sol: 100\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>RC Constructor</color> - transporter rover that can construct buildings\n- <color em>Metals Refinery</color> - slowly converts Waste Rock into Metals\n- All building costs reduced by 20%\n- Bonus Tech: <color em>Low-G Engineering</color> (unlocks Medium Dome)"),
	funding = 7000,
	goal_1_param_1 = "5",
	goal_2_param_1 = "50",
	goal_2_param_2 = "Polymers",
	goal_3_param_1 = "200",
	goal_4_param_1 = "4",
	goal_5_param_1 = "1000",
	goal_image_1 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_01.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_04.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/moisture_vaporator.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/drone.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/funding.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/research.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/funding.tga",
	group = "Default",
	id = "ISRO",
	initial_applicants = 150,
	initial_rockets = 3,
	initial_techs_unlocked = 1,
	lock_name1 = "RCConstructor",
	lock_value1 = "unlocked",
	pod_class = "SupplyPod",
	precious_metals_export_price = 24,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 4,
		'Prefab', "MoistureVaporator",
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 25,
		'Prefab', "DronePrefab",
	}),
	reward_effect_3 = PlaceObj('RewardFunding', nil),
	reward_effect_4 = PlaceObj('RewardResearchPoints', {
		'Amount', 8000,
	}),
	reward_effect_5 = PlaceObj('RewardFunding', {
		'Amount', 2000000000,
	}),
	sponsor_goal_1 = "ConstructDomeTimmed",
	sponsor_goal_2 = "ProduceResource",
	sponsor_goal_3 = "BuildingsVolume",
	sponsor_goal_4 = "DomeSpires",
	sponsor_goal_5 = "ConvertWasteRock",
	sponsor_nation_name1 = "Indian",
	sponsor_nation_name2 = "Chinese",
	sponsor_nation_name3 = "English",
	sponsor_nation_percent1 = 90,
	sponsor_nation_percent2 = 5,
	sponsor_nation_percent3 = 5,
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "LowGEngineering",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "Concrete_cost_modifier",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "Electronics_cost_modifier",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "MachineParts_cost_modifier",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "Metals_cost_modifier",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "Polymers_cost_modifier",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = -20,
		Prop = "PreciousMetals_cost_modifier",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	CostModifierPercent = 50,
	DroneHub = 1,
	Electronics = 10,
	ExplorerRover = 1,
	FreeSpaceLeft = -15000,
	FuelFactory = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	OrbitalProbe = 2,
	Polymers = 15,
	RCRover = 2,
	SortKey = 11000,
	StirlingGenerator = 1,
	WeightCostModifierGroup = "Rovers",
	WeightModifierPercent = 50,
	banners_name = "Japan",
	cargo = 50000,
	challenge_mod = 200,
	colony_color_scheme = "cherry_blossom",
	comment = "Japan(Override)",
	default_logo = "Japan",
	default_skin = "Star",
	difficulty = T(432438830304, --[[ModItemMissionSponsorPreset Default Japan difficulty]] "IV"),
	display_name = T(106355828223, --[[ModItemMissionSponsorPreset Default Japan display_name]] "Japan"),
	drone_class = "FlyingDrone",
	effect = T(244683407460, --[[ModItemMissionSponsorPreset Default Japan effect]] "Research per Sol: 100\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- <color em>Wasp Drone</color> - faster, flying drone\n- <color em>Automatic Metals Extractor</color> - a Metal Extractor that doesn't require workforce\n- Rovers - cost and weight lowered by 50%\n- Exploring a sector grants research points\n- All specialists perform better (+10 performance)\n- Applicant generation reduced <color em>(drawback)</color>"),
	funding = 6000,
	goal_1_param_1 = "6",
	goal_1_param_2 = "SensorTower",
	goal_3_param_1 = "40",
	goal_4_param_1 = "100",
	goal_5_param_1 = "2000",
	goal_image_1 = "UI/Messages/Goals/mission_goal_07.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_03.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_02.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/wasp_drone.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/martian_university.tga",
	goal_pin_image_3 = "UI/Icons/Buildings/research.tga",
	goal_pin_image_4 = "UI/Icons/Buildings/mega_trigon_dome.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/funding.tga",
	group = "Default",
	id = "Japan",
	initial_applicants = 50,
	initial_rockets = 1,
	initial_techs_unlocked = 1,
	lock_name1 = "FlyingDrone",
	lock_name2 = "Drone",
	lock_value1 = "unlocked",
	lock_value2 = "locked",
	new_in = "gagarin",
	pod_class = "SupplyPod",
	precious_metals_export_price = 20,
	research_points_per_explored_sector = 500,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 15,
		'Prefab', "DronePrefab",
	}),
	reward_effect_2 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "MartianUniversity",
	}),
	reward_effect_3 = PlaceObj('RewardSponsorResearch', {
		'Amount', 200,
	}),
	reward_effect_4 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeMegaTrigon",
	}),
	reward_effect_5 = PlaceObj('RewardFunding', {
		'Amount', 2000000000,
	}),
	specialist_bonus_performance = 10,
	specialist_bonus_performance_name = T(527010380082, --[[ModItemMissionSponsorPreset Default Japan specialist_bonus_performance_name]] "Japanese"),
	sponsor_goal_1 = "MultipleBuildings",
	sponsor_goal_2 = "OneOfEachFactory",
	sponsor_goal_3 = "MartianbornEducate",
	sponsor_goal_4 = "DeepScanSectors",
	sponsor_goal_5 = "ProduceAdvancedResources",
	sponsor_nation_name1 = "Japanese",
	sponsor_nation_percent1 = 100,
	PlaceObj('Effect_ModifyLabel', {
		Label = "Consts",
		Percent = 100,
		Prop = "ApplicantGenerationInterval",
	}),
}),
PlaceObj('ModItemMissionSponsorPreset', {
	AdvancedStirlingGenerator = 1,
	Drone = 6,
	DroneHub = 1,
	Electronics = 10,
	ExplorerRover = 1,
	MachineParts = 15,
	MoistureVaporator = 1,
	Polymers = 15,
	RCRover = 1,
	RCTransport = 1,
	SortKey = 1001,
	banners_name = "IMM",
	cargo = 70000,
	comment = "IMM(Override)",
	default_logo = "IMM",
	difficulty = T(662523644365, --[[ModItemMissionSponsorPreset Default IMM difficulty]] "I"),
	display_name = T(740991172293, --[[ModItemMissionSponsorPreset Default IMM display_name]] "International Mars Mission"),
	effect = T(328919291387, --[[ModItemMissionSponsorPreset Default IMM effect]] "Research per Sol: 300\nRare Metals price: $<ExportPricePreciousMetals> M\n\n- Uses lots sponsor's Special Units and buildings.\n- Colonists never get Earthsick\n- Food supply from Passenger Rockets increased (x10)\n- Rockets synthesize Fuel"),
	flavor = T(792311152983, --[[ModItemMissionSponsorPreset Default IMM flavor]] "Recommended for first-time players"),
	funding = 30000,
	goal_1_param_1 = "30",
	goal_4_param_1 = "3000",
	goal_5_param_1 = "10",
	goal_image_1 = "UI/Messages/Goals/mission_goal_09.tga",
	goal_image_2 = "UI/Messages/Goals/mission_goal_06.tga",
	goal_image_3 = "UI/Messages/Goals/mission_goal_05.tga",
	goal_image_4 = "UI/Messages/Goals/mission_goal_08.tga",
	goal_image_5 = "UI/Messages/Goals/mission_goal_10.tga",
	goal_pin_image_1 = "UI/Icons/Buildings/dome.tga",
	goal_pin_image_2 = "UI/Icons/Buildings/supply_pod.tga",
	goal_pin_image_3 = "UI/Icons/Colonists/Femaleengineer.tga",
	goal_pin_image_4 = "UI/Icons/Colonists/Femalescientist.tga",
	goal_pin_image_5 = "UI/Icons/Buildings/mega_dome.tga",
	group = "Default",
	id = "IMM",
	initial_applicants = 200,
	initial_rockets = 4,
	initial_techs_unlocked = 1,
	lock_name1 = "AdvancedStirlingGenerator",
	lock_value1 = "unlocked",
	name = "IMM",
	pod_class = "SupplyPod",
	research_points = 300,
	reward_effect_1 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeBasic",
	}),
	reward_effect_2 = PlaceObj('RewardSupplyPods', {
		'Amount', 5,
	}),
	reward_effect_3 = PlaceObj('RewardApplicants', {
		'Amount', 30,
		'Specialization', "engineer",
	}),
	reward_effect_4 = PlaceObj('RewardApplicants', {
		'Amount', 30,
		'Specialization', "scientist",
	}),
	reward_effect_5 = PlaceObj('RewardPrefab', {
		'Amount', 1,
		'Prefab', "DomeMega",
	}),
	rocket_class = "ZeusRocket",
	sponsor_goal_1 = "Colonists",
	sponsor_goal_2 = "ChildBorn",
	sponsor_goal_3 = "OneOfEachFactory",
	sponsor_goal_4 = "GenerateDailyRP",
	sponsor_goal_5 = "MartianbornEducate",
	sponsor_nation_name1 = "American",
	sponsor_nation_name2 = "German",
	sponsor_nation_name3 = "Russian",
	sponsor_nation_name4 = "Chinese",
	sponsor_nation_name5 = "Indian",
	sponsor_nation_name6 = "Bulgarian",
	sponsor_nation_name7 = "Swedish",
	sponsor_nation_name8 = "French",
	sponsor_nation_percent1 = 20,
	sponsor_nation_percent2 = 5,
	sponsor_nation_percent3 = 5,
	sponsor_nation_percent4 = 20,
	sponsor_nation_percent5 = 20,
	sponsor_nation_percent6 = 5,
	sponsor_nation_percent7 = 5,
	sponsor_nation_percent8 = 5,
}),
PlaceObj('ModItemTechPreset', {
	SortKey = 19,
	__copy_group = "Engineering",
	comment = "Chemistry1",
	group = "ESS_Chemistry",
	id = "Chemistry1",
	position = range(1, 1),
}),
PlaceObj('ModItemTechPreset', {
	SortKey = 5,
	__copy_group = "",
	comment = "Architecture1",
	display_name = T(347593515097, --[[ModItemTechPreset Architecture1 display_name]] "Low-G High-rise"),
	group = "ESS_Architecture",
	id = "Architecture1",
	position = range(1, 1),
}),
PlaceObj('ModItemTechPreset', {
	comment = "Computing1",
	group = "ESS_Computing",
	id = "Computing1",
	position = range(1, 1),
}),
PlaceObj('ModItemTechPreset', {
	comment = "Applicant1",
	group = "ESS_Applicant_Gathering",
	id = "Applicant1",
	position = range(1, 1),
}),
PlaceObj('ModItemTechPreset', {
	comment = "Singularity Matter",
	group = "ESS_Singularity",
	id = "ESS_Singularity_Matter",
	position = range(1, 1),
}),
}
